import type { Metadata } from "next";
import Providers from "./providers";
import PageTransition from "@/components/PageTranstion";
import Sidebar from "@/components/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Portofolio - PortoStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="flex w-screen h-screen overflow-hidden bg-surface">
            <Sidebar />
            <PageTransition>
              <main className="py-24 pr-16 h-screen">{children}</main>
            </PageTransition>
          </div>
        </Providers>
      </body>
    </html>
  );
}
