import type { Metadata } from "next";
import Providers from "./providers";
import Footer from "@/components/footer";
import "./globals.css";


export const metadata: Metadata = {
  title: "Portofolio - PortoStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white/5">
        <Providers>
          <main className="relative">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
